export enum ErrorCode {
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    INVALID_TASK_STATUS = 'INVALID_TASK_STATUS',
    INVALID_TASK_PRIORITY = 'INVALID_TASK_PRIORITY',

    NOTE_NOT_FOUND = 'NOTE_NOT_FOUND',
    NOTE_TOO_LONG = 'NOTE_TOO_LONG',

    DATABASE_ERROR = 'DATABASE_ERROR',
}